"""main"""
def main():
    """mafia sequence N"""
    size = int(input())
    if size == 1:
        print("**")
    elif size == 2:
        print("**")
    elif size == 3:
        print("* *")
        print("***")
        print("* *")
    elif size == 4:
        print("*  *")
        print("** *")
        print("* **")
        print("*  *")
    elif size == 4:
        print("*   *")
        print("**  *")
        print("* * *")
        print("*  **")
        print("*   *")
    elif size == 5:
        print("*    *")
        print("**   *")
        print("* *  *")
        print("*  * *")
        print("*   **")
        print("*    *")
    elif size == 6:
        print("*     *")
        print("**    *")
        print("* *   *")
        print("*  *  *")
        print("*   * *")
        print("*    **")
        print("*     *")
    elif size == 6:
        print("*      *")
        print("**     *")
        print("* *    *")
        print("*  *   *")
        print("*   *  *")
        print("*    * *")
        print("*     **")
        print("*      *")
    elif size == 7:
        print("*       *")
        print("**      *")
        print("* *     *")
        print("*  *    *")
        print("*   *   *")
        print("*    *  *")
        print("*     * *")
        print("*      **")
        print("*       *")
    elif size == 7:
        print("*        *")
        print("**       *")
        print("* *      *")
        print("*  *     *")
        print("*   *    *")
        print("*    *   *")
        print("*     *  *")
        print("*      * *")
        print("*       **")
        print("*        *")
    elif size == 8:
        print("*         *")
        print("**        *")
        print("* *       *")
        print("*  *      *")
        print("*   *     *")
        print("*    *    *")
        print("*     *   *")
        print("*      *  *")
        print("*       * *")
        print("*        **")
        print("*         *")
    elif size == 9:
        print("*          *")
        print("**         *")
        print("* *        *")
        print("*  *       *")
        print("*   *      *")
        print("*    *     *")
        print("*     *    *")
        print("*      *   *")
        print("*       *  *")
        print("*        * *")
        print("*         **")
        print("*          *")
    elif size == 10:
        print("*           *")
        print("**          *")
        print("* *         *")
        print("*  *        *")
        print("*   *       *")
        print("*    *      *")
        print("*     *     *")
        print("*      *    *")
        print("*       *   *")
        print("*        *  *")
        print("*         * *")
        print("*          **")
        print("*           *")
    elif size == 11:
        print("*            *")
        print("**           *")
        print("* *          *")
        print("*  *         *")
        print("*   *        *")
        print("*    *       *")
        print("*     *      *")
        print("*      *     *")
        print("*       *    *")
        print("*        *   *")
        print("*         *  *")
        print("*          * *")
        print("*           **")
        print("*            *")
    elif size == 12:
        print("*             *")
        print("**            *")
        print("* *           *")
        print("*  *          *")
        print("*   *         *")
        print("*    *        *")
        print("*     *       *")
        print("*      *      *")
        print("*       *     *")
        print("*        *    *")
        print("*         *   *")
        print("*          *  *")
        print("*           * *")
        print("*            **")
        print("*             *")
    elif size == 13:
        print("*              *")
        print("**             *")
        print("* *            *")
        print("*  *           *")
        print("*   *          *")
        print("*    *         *")
        print("*     *        *")
        print("*      *       *")
        print("*       *      *")
        print("*        *     *")
        print("*         *    *")
        print("*          *   *")
        print("*           *  *")
        print("*            * *")
        print("*             **")
        print("*              *")
    elif size == 14:
        print("*               *")
        print("**              *")
        print("* *             *")
        print("*  *            *")
        print("*   *           *")
        print("*    *          *")
        print("*     *         *")
        print("*      *        *")
        print("*       *       *")
        print("*        *      *")
        print("*         *     *")
        print("*          *    *")
        print("*           *   *")
        print("*            *  *")
        print("*             * *")
        print("*              **")
        print("*               *")
    elif size == 15:
        print("*                *")
        print("**               *")
        print("* *              *")
        print("*  *             *")
        print("*   *            *")
        print("*    *           *")
        print("*     *          *")
        print("*      *         *")
        print("*       *        *")
        print("*        *       *")
        print("*         *      *")
        print("*          *     *")
        print("*           *    *")
        print("*            *   *")
        print("*             *  *")
        print("*              * *")
        print("*               **")
        print("*                *")
    elif size == 16:
        print("*                 *")
        print("**                *")
        print("* *               *")
        print("*  *              *")
        print("*   *             *")
        print("*    *            *")
        print("*     *           *")
        print("*      *          *")
        print("*       *         *")
        print("*        *        *")
        print("*         *       *")
        print("*          *      *")
        print("*           *     *")
        print("*            *    *")
        print("*             *   *")
        print("*              *  *")
        print("*               * *")
        print("*                **")
        print("*                 *")
    elif size == 17:
        print("*                  *")
        print("**                 *")
        print("* *                *")
        print("*  *               *")
        print("*   *              *")
        print("*    *             *")
        print("*     *            *")
        print("*      *           *")
        print("*       *          *")
        print("*        *         *")
        print("*         *        *")
        print("*          *       *")
        print("*           *      *")
        print("*            *     *")
        print("*             *    *")
        print("*              *   *")
        print("*               *  *")
        print("*                * *")
        print("*                 **")
        print("*                  *")
    elif size == 18:
        print("*                   *")
        print("**                  *")
        print("* *                 *")
        print("*  *                *")
        print("*   *               *")
        print("*    *              *")
        print("*     *             *")
        print("*      *            *")
        print("*       *           *")
        print("*        *          *")
        print("*         *         *")
        print("*          *        *")
        print("*           *       *")
        print("*            *      *")
        print("*             *     *")
        print("*              *    *")
        print("*               *   *")
        print("*                *  *")
        print("*                 * *")
        print("*                  **")
        print("*                   *")
    elif size == 19:
        print("*                    *")
        print("**                   *")
        print("* *                  *")
        print("*  *                 *")
        print("*   *                *")
        print("*    *               *")
        print("*     *              *")
        print("*      *             *")
        print("*       *            *")
        print("*        *           *")
        print("*         *          *")
        print("*          *         *")
        print("*           *        *")
        print("*            *       *")
        print("*             *      *")
        print("*              *     *")
        print("*               *    *")
        print("*                *   *")
        print("*                 *  *")
        print("*                  * *")
        print("*                   **")
        print("*                    *")
    elif size == 20:
        print("*                     *")
        print("**                    *")
        print("* *                   *")
        print("*  *                  *")
        print("*   *                 *")
        print("*    *                *")
        print("*     *               *")
        print("*      *              *")
        print("*       *             *")
        print("*        *            *")
        print("*         *           *")
        print("*          *          *")
        print("*           *         *")
        print("*            *        *")
        print("*             *       *")
        print("*              *      *")
        print("*               *     *")
        print("*                *    *")
        print("*                 *   *")
        print("*                  *  *")
        print("*                   * *")
        print("*                    **")
        print("*                     *")

main()
